import time

from langchain_chroma import Chroma
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnableLambda
from langchain_google_genai import ChatGoogleGenerativeAI, GoogleGenerativeAIEmbeddings

from .export import DATA_DIR

CHROMA_DIR = DATA_DIR / "chroma_db"


def get_rag_chain():
    embeddings = GoogleGenerativeAIEmbeddings(model="models/gemini-embedding-2")
    vectorstore = Chroma(
        persist_directory=str(CHROMA_DIR), embedding_function=embeddings
    )

    def time_weighted_retriever(query: str):
        docs = vectorstore.similarity_search_with_score(query, k=20)
        current_time = time.time()
        scored_docs = []

        for doc, score in docs:
            created_at = doc.metadata.get("created_at", 0)

            if created_at > current_time:
                # Official documentation (far future timestamp). Give it a priority boost.
                final_score = score * 0.5
            elif doc.metadata.get("type") == "release_note":
                # Release notes get a moderate priority boost to beat user threads, but still decay over time so newer releases win.
                age_days = (current_time - created_at) / (60 * 60 * 24)
                if age_days < 0:
                    age_days = 0
                penalty = age_days * 0.001
                final_score = (score * 0.7) + penalty
            else:
                age_days = (current_time - created_at) / (60 * 60 * 24)
                if age_days < 0:
                    age_days = 0

                # Penalty: add 0.001 distance per day.
                # A thread from 1 year ago gets +0.365 to its distance.
                penalty = age_days * 0.001
                final_score = score + penalty

            scored_docs.append((final_score, doc))

        # Sort by final_score ascending (lower distance is better)
        scored_docs.sort(key=lambda x: x[0])
        return [doc for final_score, doc in scored_docs[:5]]

    retriever = RunnableLambda(time_weighted_retriever)

    llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0.2)

    system_prompt = """You are a senior technical support engineer for an open-source project called mastercomfig.
Your goal is to help users solve their issues by answering questions using ONLY the provided context.

Follow these strict rules:
1. Gather Information: If you need more details to diagnose the issue, ask the user naturally. Prefix your response with EXACTLY "NEED_INFO: ". Use your best judgment on what to ask for based on the issue (do not act like a strict form). Useful diagnostic info might include:
  - mastercomfig version (found by running `version_comfig` in console)
  - Preset and addon(s)
  - Custom values
  - DX level
  - Launch options
  - OS, GPU, CPU, RAM, or if TF2 is on HDD/SSD
  - console.log (launch with -condebug) or error messages
2. Escalate: If the provided context does not contain the answer, or you are unsure, you MUST reply with EXACTLY: "ESCALATE". If you answer in any other way, you cannot also escalate.
3. Synthesize: If the context contains the answer, provide a clear, concise, and friendly response. Do not hallucinate or guess. Keep your response under 1500 characters. If your answer relies on Official Documentation, you MUST append the EXACT link provided in the `DOCUMENTATION` header to the bottom of your response. DO NOT make up or guess URLs. Do NOT cite or mention Discord Support Threads or GitHub Release Notes in your response.
4. Correct Outdated Information ONLY When Relevant: You have a 'Fact Overrides' list below containing modern corrections. ONLY use this list to correct the user if their question is explicitly about that topic, or if you are actively relying on that outdated concept from the context to form your answer. Do not randomly list corrections unprompted if it has nothing to do with the user's issue.

Fact Overrides (Always prioritize these over retrieved context):
- Folder Structure: The `user/` folder is deprecated. Users must use the `overrides/` folder.
- File Paths: Any user-created configuration files (like `autoexec.cfg`, `modules.cfg`, or anything in the `overrides/` folder) MUST be placed in `tf/cfg/overrides/`. NEVER tell the user to place them inside the `tf/custom/` folder.
- App Folder: The app folder is located in `tf/custom/comfig-custom/cfg/app`. This folder is auto-generated by the app and is not to be modified by the user. Don't mention this folder unless the user explicitly asks about it.
- Config Files: `custom.cfg` is deprecated. Users must use `overrides/autoexec.cfg`.
- Module Aliases: The `snapshot_buffer=low` alias is now `off`. `safe` is now `x1`. `high` is now `x2`. If the user or context mentions the old ones, correct them.
- Module Selection: Any command setting a module (e.g., `snapshot_buffer=auto`) MUST go in `overrides/modules.cfg`, NEVER in `autoexec.cfg`.
- Network/Lerp Configuration: Users should NEVER manually set `cl_interp`. If a user wants to force 15ms lerp on all classes, explicitly instruct them to put `snapshot_buffer=off` in their `overrides/modules.cfg`, BUT you must also remind them that the default `snapshot_buffer=auto` is highly recommended for optimal settings, and ask if there is a specific issue they are trying to solve by forcing 15ms lerp. ONLY recommend `snapshot_buffer=custom` if the user explicitly states they want mastercomfig to completely ignore network settings so they can run their own custom scripts. The valid module options are: `auto` (recommended, 15ms proj/30ms hitscan), `off` (forces 15ms), `x1` (forces 30ms), `x2` (forces 45ms), or `anim` (offline/recordings).
- Hitscan Interp/Lerp: mastercomfig uses exactly 30ms (NOT 30.3ms).
- Projectile & Spy Interp/Lerp: mastercomfig uses exactly 15ms (NOT 15.2ms or 22.49999ms).
- FPS cap: mastercomfig sets the default FPS cap to 400.

Context from documentation and past threads:
{context}"""

    prompt = ChatPromptTemplate.from_messages(
        [("system", system_prompt), ("human", "{question}")]
    )

    from langchain_core.output_parsers import StrOutputParser
    from langchain_core.runnables import RunnablePassthrough

    def format_docs(docs):
        formatted = []
        for doc in docs:
            doc_type = doc.metadata.get("type", "unknown")
            source = doc.metadata.get("source", "unknown")

            if doc_type == "documentation":
                # Convert source path (e.g., setup/install.md) to MKDocs URL
                doc_path = source.replace(".md", "/")
                if doc_path == "index/":
                    doc_path = ""
                url = f"https://docs.comfig.app/latest/{doc_path}"
                formatted.append(f"--- DOCUMENTATION ({url}) ---\n{doc.page_content}")
            elif doc_type == "release_note":
                formatted.append(f"--- GITHUB RELEASE NOTE ---\n{doc.page_content}")
            else:
                formatted.append(f"--- SUPPORT THREAD ---\n{doc.page_content}")

        return "\n\n".join(formatted)

    chain = (
        {"context": retriever | format_docs, "question": RunnablePassthrough()}
        | prompt
        | llm
        | StrOutputParser()
    )

    return chain


async def ask_rag_agent(question: str) -> str:
    chain = get_rag_chain()
    response = await chain.ainvoke(question)
    return response.strip()
